project:
  type: website
  output-dir: docs
  
website:
  title: "MVEN10-lectures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Intro lecture.qmd
      - Course introduction.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

