project:
  type: website
  output-dir: docs
  
website:
  title: "MVEN10-lectures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Course introduction.qmd
        text: Course introduction
        target: "_blank"
      - href: Intro lecture.qmd
        text: Introduction to risk assessment with human and ecological endpoints
        target: "_blank"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

