---
title: "Course introduction MVEN10"
author: "Ullrika Sahlin"
date: 2024 Sept 2
format: revealjs
---

## Welcome to Risk Assessment in Environment and Public Health

-   Course coordinator: Ullrika Sahlin

-   Course platform <https://canvas.education.lu.se/courses/29367>

-   Course syllabus <https://kursplaner.lu.se/pdf/kurs/en/MVEN10/1>

## Why study risk assessment

::: incremental
-   To be competitive on the job market

    -   there is a lot of experts, but fewer experts on risk assessment

-   To better understand what expertise is required when assessing risk

    -   motivation to become an expert
    -   strengthen your interdisciplinary perspective

-   To be able to contribute to better management, including assessment and communication, of things that matter

-   To become a better decision maker
:::

## Risk assessment types

-   Human health Risk Assessment (HRA)

-   Environmental/Ecological Risk Assessment (ERA)

-   Red List Assessment (RLA)

-   Pest Risk Assessment (PRA)

## Lectures

-   Eleven lectures
-   Occupational and Health Medicine
-   Environmental Science (CEC)
-   Biology

## Book and literature seminars

-   Three book seminars
-   Two literature seminars
-   Seminars are compulsory
-   Report according to instructions
-   Come prepared!

## Exercises

-   Ten exercise occasions
-   You are expected to use your own computer (notify!)
-   Material published on canvas
-   Exercises are compulsory
-   Report according to instructions

## Team Based Learning and Case studies

-   Case studies: Risk assessments of the four different types

-   First TBL activity in class:

    -   Become familiar with four assessment types
    -   Report reflections on your own learning

-   Second TBL activity:

    -   Deepened your understanding of one of the assessment types
    -   Report as a presentation and written report to be shared with all students
    -   Padlet

## Individual project

-   Reproduce parts of an existing risk assessment, but with a slight modification.
-   Assess uncertainty in the conclusion by expert judgement for communication to risk managers
-   Written report
-   Student peer-review

## Tools

-   Open source tools for scientific assessment
    -   Excel
    -   R
    -   Tool of your own choice

## Course literature

-   Burgman, Mark. Risks and decisions for conservation and environmental management. Cambridge University Press, 2005.

-   Literature for seminars

-   Other material handed out during the course

-   Explicit references from lectures

## Non-scheduled time

-   This course is 15 credits and assumes 100% study pace

-   8 hours per day

-   Non-scheduled time implies self studies

## Grading and compulsory work

-   Written exam corresponding to 7.5 hp, Grading scale: Fail, Pass, Pass with distinction

-   Exercises and Assignments corresponding to 4.5 hp, Grading scale: Fail, Pass

-   Project work corresponding to 3.0 hp, Grading scale: Fail, Pass

-   Participation in written assignments, exercises, project work and associated parts is compulsory

    -   Seminars and literature seminars are compulsory
    -   Lectures are not compulsory, but highly recommended

## Todo

1.  Choose a course representative

2.  Inform me if you need to borrow a computer during class
