---
title: "Course content"
subtitle: "MVEN10 Risk Assessment in Environment and Public Health"
author: "Ullrika Sahlin"
date: today
---

## Course Syllabus

The general aim of the course is that the student, on completion of the course, should have advanced principles and methods to identify and assess risks in the fields of environment, nature and health. The course includes risks for humans and other organisms connected to exposure to chemicals and causes and risks connected to the extinction of species. Insights into and understanding of need of scientifically based risk communication to different target groups and the importance of knowledge about risk perception to create relevant risk assessments and communication of risks in society are included as important components. The student should be able to understand on completion of the course describe and work with common risk models or tools that are used in the areas of nature, environment and health and have an understanding of how they are used to inform decision-making.

### Knowledge and understanding

On completion of the course, the student should be able to:

-   give an account of and independently apply principles and methods for risk analysis and common risk assessment models in environment, nature and health

-   give an account of needs and examples of scientifically based risk communication in society and its relation to risk perception

-   give an account of research and development for risk assessment in nature,environment and health

### Competence and skills

On completion of the course, the student should be able to:

-   use common methods for risk assessment in the fields of nature, environment and health to within given time frames, and in collaboration with experts,identify and analyse risks

-   present result of risk assessments in different applications

-   discuss different forms of communication of risks and uncertainty in society

### Judgement and approach

On completion of the course, the student should be able to:

-   critically reflect on the possibilities and limitations of risk assessments and its role in risk management in society

-   discuss ethical aspects at assessment, management and communication of risks

-   suggest needs of additional knowledge to carry out risk assessments in environment, nature and health and take responsibility for their development of knowledge

## Course content

The course deals with:

-   identification, assessment, evaluation and management of risks connected to human and other organisms' exposure to chemicals and risks connected to extinction of species

-   methods in risk analysis such as problem formulation, hazard assessment, statistical modelling, exposure modelling, dose-response modelling, modelling of dispersion of diseases (epidemiology), modelling of uptake, renewal, distributions and secretion of poisons in living organisms (toxicokinetics) and expert assessment and principles and methods for uncertainty analysis

-   risk evaluation, which includes how to in a structured way can evaluate and make tradeoffs to support decision-making

-   risk management, which includes how different societal actors prevent risks, sets regulatory thresholds and communicate risks. In addition the importance to connect risk perception in risk management and communication of risks is included.

## Subcourses in MVEN10

### "Examination"

7.5 hp Grading scale: Fail, Pass, Pass with distinction

### Exercises and Assignments

4.5 hp Grading scale: Fail, Pass

### Project work

3.0 hp Grading scale: Fail, Pass

## Course material 

### General about risk and risk assessment

#### Burgman/Book seminars

All material from the course book by Burgman covered at the book seminars. This means that you should skip the chapters that we did not cover in the seminars. 

Here I extracted the terms from the glossary in the book that is applicable for the course:

ADI, acute effect, ALARP principle, algorithm, ambiguity, anchoring, AUC, assessment endpoints, averaging, Bayesian analysis, Bayesian credible intervals, behavioural aggregation, belief, benchmark dose, benefit-cost analysis, beta distribution, binomial distribution, bioconcentration factor, bounded rationality, bounds (statistical), calibration, calibration of models, carrying capacity, central tendency, chance, chronic effects, coefficient of variation, cognitive availability, conceptual models, conditional probabilities (statistics), confidence, confidence intervals, confusion matrix, consensus, context, convergence, correlation (statistical), correlation coefficient, cost-benefit analysis, credibility, credible intervals, cumulative probabilities, decision, decision tables, Delphi technique, demographic variation, demographic stochasticity, density dependence, dependency of a variable (statistical), detectable effect sizes, deterministic model, deterministic sensitivity, dichotomoy, disagreement, dispersal, EC50, ecotoxicology, effect size, endpoints, environmental aspect, environmental effect, environmental uncertainty (in PVAs), enzyme, epistemic uncertainty, equipossible/equiprobable, evidence, expected dose, expected utility, expert, exponential distribution, exposure pathway, false negative/false positive, fecundity (PVA), final acute value, fixed probability, fixed value, free-riding, frequentist statistics, fugacity, goodness of fit, hazard, hazard index, hazard matrices, hazard probability rank, hazard quotient, hedonic pricing, hormesis, hydrolysis, hypothesis, illusofy certainty, incertitude, indeterminacy, indicators, information disagreement, interval arithmetic, interval probabilities, kent scales, LCxx, likelihood, linguistic uncertainty, LOAEL/LOEL, LOEC, management goals, MaxiMin strategy, measurement endpoint, measurement error, median, metapopulation, minimum expected population size, minimum viable population, mixing or averaging probabilities, model averaging, model uncertainty, monitoring, Monte Carlo analysis, motivational bias, multi-criteria decision analysis, natural death (in behavioural aggregation), natural variation, negotiation, NOEL/NOEC, normal distribution, normative expertise, normative theories (of rational consensus), numerical aggregation, odds ration, partitioning coefficient, paternalistic model for stakeholder involvement, photolysis, plausibility, point estiamtes, Poisson distribution, Poisson process, Population viability analysis, possibility, posterior probabilities, power (statistical), precautionary principle, prediction intervals, principle of insufficient reason, prior probabilities, probability, probability density function, problem formulation, procedures guide (for expert elicitation), process model, prosecutor's fallacy
public participation, QSAR, quantiles, quartiles, range (statisical), rank correlations, rational consensus, reasonable maximum exposure, reference dose, reference lottery, regret, relative risk, risk, risk analysis, risk assessment, risk aversion, risk efficiency, risk equity, risk ranking, robust decisions, ROC, scenario analysis, scenarios, semantic disagreement, sensitivity analysis (for models), sigmodial curve, snowballing, Spearman rank correlation, stakeholder, stakeholder expert, stochastic models, strategic risk managment, stressors, SAR, subjective belief, substantive expertise, sure bounds, systematic error, tendency, theory-based inference, transformation, triangular distribution, type I/type II errors, underspecificity, uniform distribution, utilities, utility function, utility-based criteria, vagueness, validation/verification (of a model), variability, volatilization, zero risk strategies.


#### Material from exercises 

Principles and methods for uncertainty analysis that we have worked with during exercises. Go back and read the exercises. 

#### Additional lecture material provided by Ullrika during the course 

TO BE FURTHER UPDATED

#### Lectures about risk, uncertainty and decision making 

TO BE FURTHER UPDATED

#### Actual risk assessments

- All the assessments considered in the case study seminars 

- All the assessment considered in the individual projects

- Read the assessments and see the concepts and methods used in practice

- You will have access to the final reports by the groups.

- You have written your own report and reviewed a report by another student.

### Health risk assessment

This includes assessment on human endpoints. In the course, we primary focus is exposure to chemicals. 

- Relevant material from the general parts

- Material from lectures and literature seminars 

- Health risk assessment exercise 

TO BE FURTHER UPDATED

### Environmental risk assessment

In this course environmental risk assessment covers 

- Red list assessments (classification of status of species)
- Pest risk assessments (introduction, establishment and spread of pests or invasive species)
- Ecological risk assessment (effect on ecological systems from chemical exposure)

- Relevant material from the general parts 

TO BE FURTHER UPDATED

## Guiding study questions

NOTE: THIS IS NOT AN EXHAUSTIVE LIST OF POSSIBLE QUESTIONS THAT CAN BE ASKED AT THE EXAM. 

This list of guiding study questions has been constructed from the course syllabus (kursplanen)



- Give an account of (i.e. describe or explain) **a principle or method brought up during the course**, e.g. EC50, MOET, Model averaging or Monte Carlo simulation!

- Give an account of common risk assessment models used for **any of the types of assessments covered in the course** (Human risk assessment related to exposure to chemicals, Ecological risk assessment, Pest risk assessment, Red list assessment)!

- Give an account of factors explaining differences in risk perception!

- Give an account of recommendations to guide risk communication!

- Give an account of challenges in implementing uncertainty analysis, ensuring public trust and applying the precautionary principle!

- Evaluate **an application of an assessment** (material will be provided) in light of guidance for that assessment! Were guidelines followed? Reflect on limitations of the assessment. Suggest possible modifications of the assessment. 

- Evaluate on the presentation of result of **an application of an assessment** (material will be provided) in light of recommendations for communication. Were guidelines/recommendations followed. Suggest improvements for communicating results in the assessment. Suggestion communication to the public. 

- Comment on the role of **an application of an assessment** (material will be provided) to support a particular risk management decision. How is information from the assessment used to support the decision making? What is the decision problem. Suggest how to handle uncertainty in this particular decision problem. 

