---
title: "Introduction to individual projects"
author: "Ullrika Sahlin"
date: today
---

## General instructions

On Monday, you will be assigned one of the following risk assessments. The assignment will consider you preference, but all risk assessments must be chosen at the end as they represent material for the course.

Reproduce the indicated part of the assessment with your choice of modification.

Produce a report on 2 - 10 pages (min 2 and max 10) including figures and tables.

Provide your code for the assessment as an appendix.

Include references, including reference to suitable guidance documents for this type of risk assessment.

Refer to sections, figures and tables in the original assessment the when using it as reference.

See the [template report](../pages/report_template.qmd) for further info

## A human health risk assessment from chemicals in the food chain

Risk assessment of N‐nitrosamines in food [Link to the assessment](https://efsa.onlinelibrary.wiley.com/doi/full/10.2903/j.efsa.2023.7884)

This is a typical risk assessment of risk to human health via dietary exposure from a chemical substance in food.

The task is to replicate the risk assessment with one of the following modifications

-   a new Benchmark Dose Modelling where you discuss the influence of choices made in the modelling

-   a quantitative uncertainty analysis on the exposure assessment

At the end, quantify the level of certainty that exposure of N‐nitrosamines can lead to adverse outcomes for different proportions of the EU population. Use expert judgement where you and two other persons act as experts.

## A pest categorisation of an invasive species

Pest categorisation of the red fire ant [Link to the assessment](https://efsa.onlinelibrary.wiley.com/doi/full/10.2903/j.efsa.2023.7998)

The task is to replicate the assessment of pest potential for entry, establishment and spread in the EU (Section 3.4) with one of the following modifications

-   make your own assessment of climate matching e.g. by running the CLIMEX modelling with occurrence data that you retrieve from databases.\
    <!-- https://www.sciencedirect.com/science/article/pii/S1574954120301461 -->

<!-- https://gd.eppo.int/taxon/SOLEIN/distribution -->

At the end, quantify the level of certainty that this species will be a problem in Sweden within 20 years from now using expert judgement where you and two other persons act as experts.

## An evaluation of control measures for a disease

This assessment compares the efficiency of control measures for the African Swine Fever [Link to the assessment](https://efsa.onlinelibrary.wiley.com/doi/full/10.2903/j.efsa.2021.6707)

The task is to replicate the assessment of the Minimum radius of restricted zones and duration of the disease control measures in restricted zones (ToR 3) with the following modifications

<!-- The task is to replicate the assessment of the Monitoring period (ToR 2) OR the Minimum radius of restricted zones and duration of the disease control measures in restricted zones (ToR 3) with the following modifications -->

<!-- - run your own version of the SEIR model  -->

<!-- SEIR -->

<!-- https://search.r-project.org/CRAN/refmans/genSEIR/html/SEIQRDP.html -->

<!-- https://web.pdx.edu/~gjay/teaching/mth271_2020/html/09_SEIR_model.html -->

-   with a quantitative uncertainty analysis considering the impact of uncertainty in parameters of the kernel model and the impact of uncertainty in the model structure by model averaging

At the end, quantify the level of certainty that the control measures taken for the outbreak in Sweden will succeed in containing the outbreak. Use expert judgement where you and two other persons act as experts.

## A Population Viability Assessment

This is an assessment of conservation status based on a Population Viability Assessment of the polar bear [Link to the assessment](https://www.iucnredlist.org/species/22823/14871490#assessment-information)

You can find a description of the PVA in the [Supplementary material for Ursus maritimus Red List assessment](https://www.iucnredlist.org/species/pdf/14871490/attachment)

Replicate the risk assessment for two scenarios and two subpopulations with the following modifications

-   consider uncertainty in generation length by a probability distribution instead of the mean and P95

At the end, quantify the level of certainty that there will be a decline in at least one of the subpopulations. Use expert judgement where you and two other persons act as experts.

## An environmental risk assessment from the use of a chemical product

This is an Environmental Risk Assessment of the medicine Felodipine [Link to the assessment](https://www.astrazeneca.com/content/dam/az/our-company/Sustainability/2017/felodipine.pdf)

Replicate the risk assessment with one of the following modifications

-   perform the exposure assessment with a quantitative uncertainty analysis

-   apply species sensitivity distribution on the ecotoxicological measurements

Useful documents

[ERA for medicines](https://www.ema.europa.eu/en/documents/leaflet/environmental-risk-assessment-medicines_en.pdf)

[ECHA Guidance. Characterisation of dose\[concentration\]-response for environment](https://echa.europa.eu/documents/10162/13632/information_requirements_r10_en.pdf/bb902be7-a503-4ab7-9036-d866b8ddce69)

<!-- https://www.tandfonline.com/doi/abs/10.3109/01480545.2013.870191?journalCode=idct20 -->

<!-- Other useful documents about Environmental risk assessment [ERA for medicines](https://www.ema.europa.eu/en/documents/leaflet/environmental-risk-assessment-medicines_en.pdf) -->

<!-- [Criver](https://www.criver.com/products-services/safety-assessment/environmental-safety/environmental-risk-assessment?region=3696) -->

<!-- [Criver2](https://www.criver.com/sites/default/files/resources/doc_a/EnvironmentalAssessmentofHumanPharmaceuticals.pdf) -->

At the end, quantify the level of certainty that release of Felodipine into the environment will result in adverse impact on ecosystems. Use expert judgement where you and two other persons act as experts.
